### ISSUE TITLE
Travis build matrix with gcc [4 to 8]

### ISSUE THREAD

**Issue by jeanlego** [verilog-to-routing/vtr-verilog-to-routing#595]
#### Proposed Behaviour
It seems that some issues creep in the buildbot regression because of gcc versions.

Travis offers build matrix that can run in parralel and could probably catch thos early
https://docs.travis-ci.com/user/build-matrix/

I was thinkng this might be a good idea for our use case.

I'll whip up something if there's interest.

**Comment by kmurray** [comment]
FYI, the VTR Buildbot does already check that VTR compiles [with various GCC & Clang versions](http://builds.verilogtorouting.org:8080/builders/build_configs/builds/760/steps/sweep%20build%20configurations/logs/stdio). It also checks that the code compiles correctly with various compilation flag combinations. See [the script](https://github.com/verilog-to-routing/vtr-verilog-to-routing/blob/master/sweep_build_configs.py) for details.

**Comment by mithro** [comment]
See #625

**Comment by mithro** [comment]
Example implementation can be found on my `build-compat` branch which [builds on top of the pull request #619]( https://github.com/verilog-to-routing/vtr-verilog-to-routing/pull/619).

Example output can be found at https://travis-ci.org/mithro/vtr-verilog-to-routing/builds/539520874 and seen below;

![image](https://user-images.githubusercontent.com/21212/58682678-6780c900-8326-11e9-8ade-0c344893ff73.png)

A quick look it seems like;
 - [x] GCC 5 works
 - [x] GCC 6 works
 - [ ] GCC 7 fails with issue in https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/628
 - [ ] GCC 8 fails with issue in https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/628
 - [ ] clang-3.9 currently a WIP
 - [ ] clang-6.0 currently a WIP
 - [ ] clang-8 fails with a similar issue in the linkter to https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/628

**Comment by kmurray** [comment]
Interesting. [On buildbot](http://builds.verilogtorouting.org:8080/builders/build_configs/builds/774) we build the following successfully:
* gcc: 4.9, 5, 6, 7, 8
* clang: 3.6, 3.8
* mingw-64 (gcc cross-compile to windows): 5

Any ideas about what's different between those environments?

**Comment by mithro** [comment]
@kmurray The only inconsistency there is gcc 8? Travis doesn't run the older clang or gcc 4.9

**Comment by kmurray** [comment]
Resolved with #818
